#pragma config(Motor,  port1,           RMotor,        tmotorVex393_HBridge, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           Thumb,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Claw,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           Arm,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          LMotor,        tmotorVex393_HBridge, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		//Tank Drive
		motor[RMotor]=vexRT(Ch2)*0.75;
		motor[LMotor]=vexRT(Ch3)*0.75;

		//Arm Control
		if (vexRT[Btn6U]==1)
		{
			motor[Arm]=60;
		}
		else if (vexRT[Btn6D]==1)
		{
			motor[Arm]=-60;
		}
		else
		{
			motor[Arm]=15;
		}

		//Claw Control
		if (vexRT[Btn5U]==1)
		{
			motor[Claw]=-60;
		}
		else
		{
			motor[Claw]=40;
		}

		//Thumb Control
		if (vexRT[Btn5U]==1)
		{
			motor[Thumb]=60;
		}
		else if (vexRT[Btn5D]==1)
		{
			motor[Thumb]=-30;
		}
		else
		{
			motor[Thumb]=0;
		}
	}
}
